#!/bin/bash
# S.Chekanov (ANL)

source ./setup.sh

#python2 makedata.py train1.data # training sample
#python2 makedata.py valid1.data # validation sample

# train NN using train1.data sample 
./ana train 

sleep 1

# validation and create prediction
./ana run
