#!/bin/bash
# S.Chekanov (ANL)

source ./setup.sh

PWD=`pwd`

#python2 makedata.py train1.data # training sample
#python2 makedata.py valid1.data # validation sample
#python2 makedata.py test1.data  # test sample

rm -f ./data/train.data ./data/test.data

# use fake data
# ln -s $PWD/data/train1.data $PWD/data/train.data; ln -s $PWD/data/test1.data  $PWD/data/test.data

# use real Delphes
cd data
ln -s ../../makedata/out_ann_rfast007/jet_pt_v0.d train.data; 
ln -s ../../makedata/out_ann_rfast007/jet_pt_v1.d test.data
cd ..


# train NN using train1.data sample 
./ana train 

sleep 1

# validation and create prediction
./ana run
